initial_setup_dest: /home/odin/initial_setup.sh

initial_setup_defaults:
  can_interfaces:
    can0:
      enabled: true
      fd: false
      bitrate: 500000
      sample_point: "0.8"
      sjw: 3
      berr_reporting: true
      restart_ms: 100
    can1:
      enabled: true
      fd: false 
      bitrate: 500000
      sample_point: "0.8"
      sjw: 3
      berr_reporting: true
      restart_ms: 100

  irq_affinity:
    "236":
      enabled: false
      mask: "2"
      label: "usb interrupt"
    "14":
      enabled: true
      mask: "2"
      label: "can0"
    "15":
      enabled: true
      mask: "2"
      label: "can1"

  ethtool:
    enabled: true
    target_prefix: "192.168.31."
    speed: 2500
    duplex: full
    autoneg: "on"
    advertise: "0x800000000000"

  sensor_interface: "veth0"

  vlans:
    "2":
      enabled: true
      description: "Internet interface"
      ip: "192.168.9.102/24"
      default_gw: "192.168.9.1"
    "30":
      enabled: true
      description: "Pandar64_0 interface"
      ip: "10.30.1.207/24"
    "31":
      enabled: true
      description: "Pandar64_1 interface"
      ip: "10.31.1.207/24"
    "32":
      enabled: true
      description: "OT128_0 interface"
      ip: "10.32.1.207/24"
    "33":
      enabled: true
      description: "OT128_1 interface"
      ip: "10.33.1.207/24"
    "34":
      enabled: true
      description: "XT32_0 interface"
      ip: "10.34.1.207/24"
    "35":
      enabled: true
      description: "XT32_1 interface"
      ip: "10.35.1.207/24"
    "36":
      enabled: true
      description: "XT32_2 interface"
      ip: "10.36.1.207/24"
    "37":
      enabled: true
      description: "XT32_3 interface"
      ip: "10.37.1.207/24"
    "19":
      enabled: true
      description: "ARS540 interface"
      ip: "10.13.1.166/24"
      firewall:
        - iptables -I INPUT 1 -p udp --dport 42102 -j ACCEPT

  ptp:
    enabled: true
    use_exec: false
    configs:
      hesai:
        enabled: true
        interface: "veth0"
        config: "/home/odin/ptp4l_veth0_hesai.cfg"
        log: "/var/log/ptp4l_veth0_hesai.log"
      ars:
        enabled: true
        interface: "veth0"
        config: "/home/odin/ptp4l_veth0_ars.cfg"
        log: "/var/log/ptp4l_veth0_ars.log"
