# Add only ODIM role-specific differences here.
initial_setup_overrides: 
  can_interfaces:
    can0:
      enabled: true
      fd: true
      bitrate: 500000
      sample_point: "0.75"
      sjw: 3
      dbitrate: 2000000
      dsample_point: "0.8"
      dsjw: 3
      berr_reporting: true
      restart_ms: 100
    can1:
      enabled: true
      fd: true
      bitrate: 500000
      sample_point: "0.75"
      sjw: 3
      dbitrate: 2000000
      dsample_point: "0.8"
      dsjw: 3
      berr_reporting: true
      restart_ms: 100
  vlans:
    "30":
      enabled: false
    "31":
      enabled: false 
    "32":
      enabled: false
    "33":
      enabled: false
    "34":
      enabled: false
    "35":
      enabled: false
    "36":
      enabled: false
    "37":
      enabled: false
    "19":
      enabled: false

  ptp:
    enabled: false

