[initial_setup_targets:children]
role_odim
role_odil
role_odic

[role_odim]
odim ansible_host="{{ odim_vpn_ip | mandatory }}" ansible_user=odin ansible_password="{{ ssh_pass | mandatory }}"

[role_odim:vars]
initial_setup_config_role=role_odim

[role_odil]
odil ansible_host=192.168.31.7 ansible_user=odin ansible_password="{{ ssh_pass | mandatory }}" ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="sshpass -p {{ ssh_pass | mandatory }} ssh -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null odin@{{ odim_vpn_ip | mandatory }}"'

[role_odil:vars]
initial_setup_config_role=role_odil

[role_odic]
odic ansible_host=192.168.31.8 ansible_user=odin ansible_password="{{ ssh_pass | mandatory }}" ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="sshpass -p {{ ssh_pass | mandatory }} ssh -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null odin@{{ odim_vpn_ip | mandatory }}"'

[role_odic:vars]
initial_setup_config_role=role_odic
